### ISSUE TITLE
Turtlebot3 follower example pickle.load error

### ISSUE THREAD

**Issue by danireagan** [ROBOTIS-GIT/turtlebot3_applications#35]
Hello Sir/Madam,

I have followed the tutorial given in this link http://emanual.robotis.com/docs/en/platform/turtlebot3/applications/ to run the turtlebot follower demo. I am able to complete all the steps but in the last step when i give the command "roslaunch turtlebot3_follower turtlebot3_follower.launch", it is throwing the error 
Traceback (most recent call last):
  File "/home/eccf130/catkin_ws/src/turtlebot3_applications/turtlebot3_follower/nodes/follower", line 142, in <module>
    main()
  File "/home/eccf130/catkin_ws/src/turtlebot3_applications/turtlebot3_follower/nodes/follower", line 137, in main
    follow = follower()
  File "/home/eccf130/catkin_ws/src/turtlebot3_applications/turtlebot3_follower/nodes/follower", line 36, in __init__
    self.clf = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "sklearn/tree/_tree.pyx", line 601, in sklearn.tree._tree.Tree.__cinit__
ValueError: Buffer dtype mismatch, expected 'SIZE_t' but got 'long long'

When I googled the error it give answers like "pickle file is not portable across platforms". I am running the example in Ubuntu 16.04 32 bit OS, intel core i5 system. Can you share the information of the model and where it is created (32 bit or 64 bit). 

Regards
Dani

**Comment by danireagan** [comment]
Hello Sir

I have run the turtlebot follower demo in 64 bit Ubuntu OS. It is running perfectly. The parameters of the classification algorithm are tuned with 64 bit Ubuntu OS, hence earlier I was unable to run in 32 bit Ubuntu OS.

Regards
Dani
